version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ederb1.1c@gmail.com --agree-tos --no-eff-email -d survey.ederbarrios.online -d library.ederbarrios.online
    